title: Alexandra
description:

# Force GitHub to include custom CSS
include:
  - main-site.css
  - terminal.css
  - index.html
  - script.js
  - responses.json

baseurl: ""
url: "https://alexandrafernlund.github.io"

